# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bf55fc1dfeebff1476c0ec9e9c5bb4e8"
name = "faq-app"
handle = "faq-app-31"
application_url = "https://expected-unknown-bk-styles.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quandoan21.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://expected-unknown-bk-styles.trycloudflare.com/auth/callback",
  "https://expected-unknown-bk-styles.trycloudflare.com/auth/shopify/callback",
  "https://expected-unknown-bk-styles.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
